### ISSUE TITLE
possible bug

### ISSUE THREAD

**Issue by enaon** [espruino/EspruinoAppLoaderCore#1]
No sure again, I was playing and I think the oneclick install fails on the eraseall command, the espruino responds with "Erasing..", and then with "OK", but the Erasing... is causing an error. 

I've added this   
if ((result==""||result.trim()=="Erasing...")&& (timeout--)) {
to line 171 of comms.js to solve it, just reporting it in case I am not doing something wrong.

**Comment by gfwilliams** [comment]
What are you running this with - BangleApps or EspruinoApps?

If you write 'Puck.debug=3' in the console first I think you should be able to see what's actually being sent back?

**Comment by enaon** [comment]
I  am using EspruinoApps, I forked it to host my p8 scipts here, I hope it is ok :)
https://enaon.github.io/eucWatch/p8.html#

I got this from chome's console when looking for the error reason:
```
<BLE> Sent
puck.js:371 <BLE> Sending ";reset()\n"
puck.js:371 <BLE> Received "Erasing...\r\n"
puck.js:371 <BLE> Sent
puck.js:371 <BLE> Received "OK\r\n"
```

**Comment by gfwilliams** [comment]
Thanks!

But I just tried here and:

```
>require("Storage").eraseAll();
=undefined
```

So nothing prints `Erasing...` to the console. Is it possible that in the P8 watch you or someone has modified `E.showMessage` so that `E.showMessage("Erasing...");` prints to the console???

**Comment by enaon** [comment]
Yes it is strange, require("Storage").eraseAll(); gives undefined to me as well from the console, I have no clue where the Erasing... part comes from, or the OK. 

In the P8 there is no E.showMessage cmd, so I changed every E.showMessage to an console.log in comms.js.

**Comment by gfwilliams** [comment]
> so I changed every E.showMessage to an console.log in comms.js.

So yeah, that's the problem. Remove the `console.log` you added, it won't print `Erasing...` and it'll work :)

It'd actually be neat to add an `E.showMessage` for the P8, then this would work without modification.

**Comment by enaon** [comment]
thanks :)
