### ISSUE TITLE
[bug] App loader initializes with showing pretokenisation turned off but does it anyway

### ISSUE THREAD

**Issue by thyttan** [espruino/EspruinoAppLoaderCore#53]
## The bug

When starting an app loader instance for the first time in the pretokenise setting will be shown as toggled off. But when loading apps to the watch they will be pretokeised.

## Reproduce:
1. Navigate to https://espruino.github.io/BangleApps/
2. See that pretokenise is toggled off in the "More..." tab.
3. Upload an app.
4. Inspect the corresponding app file on the watch via the Web IDE (notice it's pretokenised).
5. Toggle pretokenisation option on and off in the "More..." tab.
6. Upload the app again.
7. Inspect the correspoding app file on the watch again (notice it wasn't pretokenised).

**Comment by gfwilliams** [comment]
Ok, hopefully it's fixed now. Not sure how it ever got into the state where the status was never set up correctly!
